apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: app-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
    spec:
      containers:
      - image: app-name
        name: app-name
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-name
spec:
  type: NodePort
  selector:
    app: app-name
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
